import { Download, Play, Pause } from "lucide-react"
import { useEffect, useMemo, useRef, useState } from "react"
import { trimVideo } from "@/lib/videoApi"

export default function VideoTrimCanvas({ file }: { file: File }) {
  const video = useRef<HTMLVideoElement>(null)
  const [duration, setDuration] = useState(0), [start, setStart] = useState(0), [end, setEnd] = useState(0), [current, setCurrent] = useState(0), [playing, setPlaying] = useState(false), [error, setError] = useState("")
  const source = useMemo(() => URL.createObjectURL(file), [file])
  useEffect(() => () => URL.revokeObjectURL(source), [source])
  const position = (event: React.PointerEvent) => Math.max(0, Math.min(duration, ((event.clientX - event.currentTarget.getBoundingClientRect().left) / event.currentTarget.getBoundingClientRect().width) * duration))
  const seek = (value: number) => { if (video.current) video.current.currentTime = value; setCurrent(value) }
  const toggle = () => { if (!video.current) return; video.current.paused ? video.current.play() : video.current.pause() }
  const download = async () => { try { const blob = await trimVideo(file, start, end); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `${file.name.replace(/\.[^.]+$/, "")}_trimmed.mp4`; link.click(); URL.revokeObjectURL(link.href) } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to trim video.") } }
  return <section className="absolute inset-x-6 bottom-6 top-20 flex flex-col gap-4"><video ref={video} className="min-h-0 flex-1 rounded-lg bg-black object-contain" src={source} onLoadedMetadata={(e) => { setDuration(e.currentTarget.duration); setEnd(e.currentTarget.duration) }} onTimeUpdate={(e) => { const value=e.currentTarget.currentTime; setCurrent(value); if (value >= end) { e.currentTarget.pause(); seek(start) } }} onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} />
    <div className="rounded-lg border bg-background p-4"><div className="mb-2 flex items-center justify-between text-sm"><span>{file.name}</span><span>{current.toFixed(2)} / {duration.toFixed(2)}</span></div><div className="relative h-8 touch-none" onPointerDown={(e) => seek(position(e))}><div className="absolute inset-x-0 top-3 h-2 rounded bg-muted"/><div className="absolute top-3 h-2 rounded bg-primary" style={{left:`${duration ? start/duration*100:0}%`,right:`${duration ? 100-end/duration*100:0}%`}}/><i className="absolute top-0 h-8 w-3 rounded bg-white" style={{left:`${duration ? start/duration*100:0}%`}} onPointerDown={(e)=>{e.stopPropagation(); e.currentTarget.setPointerCapture(e.pointerId); e.currentTarget.onpointermove=(move)=>setStart(Math.min(position(move as unknown as React.PointerEvent),end-.01))}}/><i className="absolute top-0 h-8 w-3 rounded bg-white" style={{left:`${duration ? end/duration*100:0}%`}} onPointerDown={(e)=>{e.stopPropagation(); e.currentTarget.setPointerCapture(e.pointerId); e.currentTarget.onpointermove=(move)=>setEnd(Math.max(position(move as unknown as React.PointerEvent),start+.01))}}/><i className="absolute top-1 h-6 w-0.5 bg-foreground" style={{left:`${duration ? current/duration*100:0}%`}}/></div><div className="mt-3 flex items-center gap-3"><button onClick={toggle} className="rounded bg-muted p-2">{playing?<Pause/>:<Play/>}</button><span className="text-sm">Trim {start.toFixed(2)} → {end.toFixed(2)}</span><button onClick={download} className="ml-auto flex items-center gap-2 rounded bg-primary px-3 py-2 text-primary-foreground"><Download className="h-4 w-4"/>Download MP4</button></div>{error&&<p className="mt-2 text-sm text-destructive">{error}</p>}</div></section>
}
